//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADC_Control.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADC_Control.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Property.
        /// </summary>
        public static string ADCPropertyColumnName {
            get {
                return ResourceManager.GetString("ADCPropertyColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value.
        /// </summary>
        public static string ADCValueColumnName {
            get {
                return ResourceManager.GetString("ADCValueColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calibration inside.
        /// </summary>
        public static string CalibrationADCInsideButtonContent {
            get {
                return ResourceManager.GetString("CalibrationADCInsideButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calibration outside.
        /// </summary>
        public static string CalibrationADCOutsideButtonContent {
            get {
                return ResourceManager.GetString("CalibrationADCOutsideButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calibration scale.
        /// </summary>
        public static string CalibrationADCScaleButtonContent {
            get {
                return ResourceManager.GetString("CalibrationADCScaleButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string CancelADCOperationButtonContent {
            get {
                return ResourceManager.GetString("CancelADCOperationButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change port.
        /// </summary>
        public static string ChangePortButtonContent {
            get {
                return ResourceManager.GetString("ChangePortButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close port.
        /// </summary>
        public static string ClosePortButtonContent {
            get {
                return ResourceManager.GetString("ClosePortButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert one value.
        /// </summary>
        public static string ConvertADCButtonContent {
            get {
                return ResourceManager.GetString("ConvertADCButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на voltage = {0}\r\n.
        /// </summary>
        public static string ConvertResultStringFormat {
            get {
                return ResourceManager.GetString("ConvertResultStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert to time.
        /// </summary>
        public static string ConvertToTimeADCButtonContent {
            get {
                return ResourceManager.GetString("ConvertToTimeADCButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Graphs.
        /// </summary>
        public static string GraphsLabelContent {
            get {
                return ResourceManager.GetString("GraphsLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Closed port.
        /// </summary>
        public static string LogClosePortFinish {
            get {
                return ResourceManager.GetString("LogClosePortFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start close port {0} .
        /// </summary>
        public static string LogClosePortStart {
            get {
                return ResourceManager.GetString("LogClosePortStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Measured successfully.
        /// </summary>
        public static string LogEndConvertGraph {
            get {
                return ResourceManager.GetString("LogEndConvertGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error measure.
        /// </summary>
        public static string LogErrorConvertGraph {
            get {
                return ResourceManager.GetString("LogErrorConvertGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string LogFinishCoonvertValue {
            get {
                return ResourceManager.GetString("LogFinishCoonvertValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finish rewind monochrome by inside timer.
        /// </summary>
        public static string LogFinishRewindByADCTimerMonochrome {
            get {
                return ResourceManager.GetString("LogFinishRewindByADCTimerMonochrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finish run monochrome by inside timer.
        /// </summary>
        public static string LogFinishRunByADCTimerMonochrome {
            get {
                return ResourceManager.GetString("LogFinishRunByADCTimerMonochrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not successfully open port {0}.
        /// </summary>
        public static string LogOpenPortError {
            get {
                return ResourceManager.GetString("LogOpenPortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open port {0}.
        /// </summary>
        public static string LogOpenPortFinish {
            get {
                return ResourceManager.GetString("LogOpenPortFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open port started.
        /// </summary>
        public static string LogOpenPortStart {
            get {
                return ResourceManager.GetString("LogOpenPortStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Readed porperties from ADC.
        /// </summary>
        public static string LogReadADCPropertiesFinish {
            get {
                return ResourceManager.GetString("LogReadADCPropertiesFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start read propertties from ADC.
        /// </summary>
        public static string LogReadADCPropertiesStart {
            get {
                return ResourceManager.GetString("LogReadADCPropertiesStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rewinded successfully.
        /// </summary>
        public static string LogRewindMonochromeFinish {
            get {
                return ResourceManager.GetString("LogRewindMonochromeFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rewind start.
        /// </summary>
        public static string LogRewindMonochromeStart {
            get {
                return ResourceManager.GetString("LogRewindMonochromeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Run monochrome successfully.
        /// </summary>
        public static string LogRunMonochromeFinish {
            get {
                return ResourceManager.GetString("LogRunMonochromeFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Run monochrome.
        /// </summary>
        public static string LogRunMonochromeStart {
            get {
                return ResourceManager.GetString("LogRunMonochromeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start measure by ADC.
        /// </summary>
        public static string LogStartConvertGraph {
            get {
                return ResourceManager.GetString("LogStartConvertGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start convert value.
        /// </summary>
        public static string LogStartConvertValue {
            get {
                return ResourceManager.GetString("LogStartConvertValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start rewind monochrome by inside timer.
        /// </summary>
        public static string LogStartRewindByADCTimerMonochrome {
            get {
                return ResourceManager.GetString("LogStartRewindByADCTimerMonochrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start run monochrome by inside timer.
        /// </summary>
        public static string LogStartRunByADCTimerMonochrome {
            get {
                return ResourceManager.GetString("LogStartRunByADCTimerMonochrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Writed proprerties to ADC.
        /// </summary>
        public static string LogWriteADCPropertiesFinish {
            get {
                return ResourceManager.GetString("LogWriteADCPropertiesFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start write read properties to ADC.
        /// </summary>
        public static string LogWriteADCPropertiesStart {
            get {
                return ResourceManager.GetString("LogWriteADCPropertiesStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open port.
        /// </summary>
        public static string OpenPortButtonContent {
            get {
                return ResourceManager.GetString("OpenPortButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Baund rate.
        /// </summary>
        public static string PortBaundRateLabel {
            get {
                return ResourceManager.GetString("PortBaundRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data bits.
        /// </summary>
        public static string PortDataBits {
            get {
                return ResourceManager.GetString("PortDataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parity.
        /// </summary>
        public static string PortParity {
            get {
                return ResourceManager.GetString("PortParity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop bits.
        /// </summary>
        public static string PortStopBitsLabel {
            get {
                return ResourceManager.GetString("PortStopBitsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rewind.
        /// </summary>
        public static string RewindMonochromeButtonContent {
            get {
                return ResourceManager.GetString("RewindMonochromeButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rewind monochrome by inside timer.
        /// </summary>
        public static string RewindMonochromeByInsideTimerButtonContent {
            get {
                return ResourceManager.GetString("RewindMonochromeByInsideTimerButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Run only monochromator.
        /// </summary>
        public static string RunMonochromeButtonContent {
            get {
                return ResourceManager.GetString("RunMonochromeButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Run monochrome by inside timer.
        /// </summary>
        public static string RunMonochromeByInsideTimerButtonContent {
            get {
                return ResourceManager.GetString("RunMonochromeByInsideTimerButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test mirror ADC.
        /// </summary>
        public static string TestMirrorCommandButtonContent {
            get {
                return ResourceManager.GetString("TestMirrorCommandButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Read.
        /// </summary>
        public static string UpdateADCProperties {
            get {
                return ResourceManager.GetString("UpdateADCProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update ports.
        /// </summary>
        public static string UpdatePortsButtonContent {
            get {
                return ResourceManager.GetString("UpdatePortsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write.
        /// </summary>
        public static string WriteADCProperties {
            get {
                return ResourceManager.GetString("WriteADCProperties", resourceCulture);
            }
        }
    }
}
