//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADC_Control_Library.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADC_Control_Library.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error UART tranfer. Please restart stm.
        /// </summary>
        internal static string ADCFailedConnect {
            get {
                return ResourceManager.GetString("ADCFailedConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Property {0} read succesfully.
        /// </summary>
        internal static string ADCReadProperty {
            get {
                return ResourceManager.GetString("ADCReadProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset comlited.
        /// </summary>
        internal static string ADCResetComplited {
            get {
                return ResourceManager.GetString("ADCResetComplited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Inside calibration is succesfully.
        /// </summary>
        internal static string LogCalibrationInsideFinish {
            get {
                return ResourceManager.GetString("LogCalibrationInsideFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start Inside Calibration.
        /// </summary>
        internal static string LogCalibrationInsideStart {
            get {
                return ResourceManager.GetString("LogCalibrationInsideStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Outside calibration is succesfully.
        /// </summary>
        internal static string LogCalibrationOutsideFinish {
            get {
                return ResourceManager.GetString("LogCalibrationOutsideFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start Outside Calibration.
        /// </summary>
        internal static string LogCalibrationOutsideStart {
            get {
                return ResourceManager.GetString("LogCalibrationOutsideStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scale calibration is succesfully.
        /// </summary>
        internal static string LogCalibrationScaleFinish {
            get {
                return ResourceManager.GetString("LogCalibrationScaleFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start scale Calibration.
        /// </summary>
        internal static string LogCalibrationScaleStart {
            get {
                return ResourceManager.GetString("LogCalibrationScaleStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace all properties.
        /// </summary>
        internal static string LogComparerADCPropertiesFinish {
            get {
                return ResourceManager.GetString("LogComparerADCPropertiesFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace properties from ADC.
        /// </summary>
        internal static string LogComparerADCPropertiesStart {
            get {
                return ResourceManager.GetString("LogComparerADCPropertiesStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert is successfully.
        /// </summary>
        internal static string LogConvertFinish {
            get {
                return ResourceManager.GetString("LogConvertFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start converting.
        /// </summary>
        internal static string LogConvertStart {
            get {
                return ResourceManager.GetString("LogConvertStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Port not open: {0}.
        /// </summary>
        internal static string LogErrorOpenPort {
            get {
                return ResourceManager.GetString("LogErrorOpenPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open port succesfully.
        /// </summary>
        internal static string LogOpenPort {
            get {
                return ResourceManager.GetString("LogOpenPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start open port.
        /// </summary>
        internal static string LogOpenPortStart {
            get {
                return ResourceManager.GetString("LogOpenPortStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Readed properties from ADC.
        /// </summary>
        internal static string LogReadFinishPropertiesFromADC {
            get {
                return ResourceManager.GetString("LogReadFinishPropertiesFromADC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start read properties from ADC.
        /// </summary>
        internal static string LogReadStartPropertiesFromADC {
            get {
                return ResourceManager.GetString("LogReadStartPropertiesFromADC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset finish.
        /// </summary>
        internal static string LogResetFinish {
            get {
                return ResourceManager.GetString("LogResetFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start reset.
        /// </summary>
        internal static string LogResetStart {
            get {
                return ResourceManager.GetString("LogResetStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rewind monochrome.
        /// </summary>
        internal static string LogRewindMonochrome {
            get {
                return ResourceManager.GetString("LogRewindMonochrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send message: port not open.
        /// </summary>
        internal static string LogSendMessageNotOpenPort {
            get {
                return ResourceManager.GetString("LogSendMessageNotOpenPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start send command {0} to ADC.
        /// </summary>
        internal static string LogSendMessageStart {
            get {
                return ResourceManager.GetString("LogSendMessageStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send message {0} continued.
        /// </summary>
        internal static string LogSendMessageSuccessfully {
            get {
                return ResourceManager.GetString("LogSendMessageSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start monochrome.
        /// </summary>
        internal static string LogStartMonochrome {
            get {
                return ResourceManager.GetString("LogStartMonochrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start read data port.
        /// </summary>
        internal static string LogStartReadDataPort {
            get {
                return ResourceManager.GetString("LogStartReadDataPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start timer in adc.
        /// </summary>
        internal static string LogStartTimerADC {
            get {
                return ResourceManager.GetString("LogStartTimerADC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop monochrome.
        /// </summary>
        internal static string LogStopMonochrome {
            get {
                return ResourceManager.GetString("LogStopMonochrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mirror test failed: timeout.
        /// </summary>
        internal static string LogTestMirrorFailedTestByTimeout {
            get {
                return ResourceManager.GetString("LogTestMirrorFailedTestByTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Receive data {0} from ADC.
        /// </summary>
        internal static string LogTestMirrorReceived {
            get {
                return ResourceManager.GetString("LogTestMirrorReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TestMirror: send data {0} to ADC.
        /// </summary>
        internal static string LogTestMirrorSend {
            get {
                return ResourceManager.GetString("LogTestMirrorSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update successfully.
        /// </summary>
        internal static string LogUpdateFromADCPropertiesFinish {
            get {
                return ResourceManager.GetString("LogUpdateFromADCPropertiesFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update from ADC start.
        /// </summary>
        internal static string LogUpdateFromADCPropertiesStart {
            get {
                return ResourceManager.GetString("LogUpdateFromADCPropertiesStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find {0} properties changed.
        /// </summary>
        internal static string LogWriteCountChangedPorperties {
            get {
                return ResourceManager.GetString("LogWriteCountChangedPorperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Writed {0} property to ADC.
        /// </summary>
        internal static string LogWritePorpertyFinish {
            get {
                return ResourceManager.GetString("LogWritePorpertyFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write changed porperty to ADC successfully.
        /// </summary>
        internal static string LogWriteProperiesFinish {
            get {
                return ResourceManager.GetString("LogWriteProperiesFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start write changed property to ADC.
        /// </summary>
        internal static string LogWritePropertiesStart {
            get {
                return ResourceManager.GetString("LogWritePropertiesStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write {0} porperty to ADC.
        /// </summary>
        internal static string LogWritePropertyStart {
            get {
                return ResourceManager.GetString("LogWritePropertyStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test failed.
        /// </summary>
        internal static string OnTestFailed {
            get {
                return ResourceManager.GetString("OnTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test successfuly.
        /// </summary>
        internal static string OnTestSuccessfuly {
            get {
                return ResourceManager.GetString("OnTestSuccessfuly", resourceCulture);
            }
        }
    }
}
